name: expression functions demo
on:
  push:
    branches:
      - main

jobs:
  expression-functions:
    runs-on: ubuntu-latest
    steps:
      - name: check if string contains substring
        if: ${{ contains(github.event.issue.title, 'llo') }}
        run: echo "The string contains the substring"
      - name: check if string starts with
        if: ${{ startsWith(github.event.issue.title, 'He') }}
        run: echo "The string starts with 'He'"
      - name: check if string ends with
        if: ${{ endsWith(github.event.issue.title, 'ld') }}
        run: echo "the string ends with 'ld'"
      - name: Format and echo string
        run: echo ${{ format('Hello {0} {1} {2}', 'Mona', 'the', 'octocat') }}
      - name: Join issue labels
        if: ${{ github.event_name == 'issues' }}
        run: |
          echo "Issue labels: ${{ join(github.event.issue.labels.*.name, ',') }}"
      - name: convert job context to JSON
        run: | 
          echo "Job context in JSON: ${{ toJSON(github.job) }}"
      - name: Parse JSON string
        run: |
          echo "Parsed JSON: ${{ fromJson('{"hello": "World"}').hello }}"
      - name: Hash Files
        run: |
          echo "Hash of files : ${{ hashFiles('**/package-lock.json', '**/Gemfile.lock') }}"
      - name: The job has succeeded
        if: ${{ success() }}
        run: echo "The job succeeded"
      - name: the job has failed
        if: ${{ failure() }}
        run: echo "the job failed"
