name: single-event
on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main
jobs:
    hello-world:
        runs-on: ubuntu
        steps:
            - name: run a one line script.
              run: echo "Hello World"
