name: cron test

on:
    schedule:
        - cron: '*/5 * * * *'
jobs:
    test_schedule:
        runs-on: ubuntu-latest
        steps:
            - name: Not every time
              if: github.event.schedule == '*/5 * * * *'
              run: echo "Its a scheduled event"
            - name: Every time
              if: github.event.schedule != '*/5 * * * *'
              run: echo "Not a 5 minute cron"