name: schedule-test

on:
    schedule:
        - cron: '*/5 * * * *'
jobs:
    test_schedule:
        runs-on: ubuntu-latest
        steps:
            - name: Not on monday or wednesday
              if: github.event.schedule == '*/5 * * * *'
              run: echo "Its a scheduled event"