name: Print GitHub Token
on: push

jobs:
  print-token:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Print GitHub Token
        run: echo "GITHUB_TOKEN is ${{ secrets.GITHUB_TOKEN }}"
